network:
  name: case2_simple
  source: pglib
  network_dir: none

settings:
  mode: pf
  data_dir: ./data_out_case2_simple_base
  num_processes: 8
  max_iter: 300
  pf_fast: false
  dcpf_fast: true
  seed: 42
  overwrite: true
  large_chunk_size: 1000
  include_dc_res: true
  enable_solver_logs: true

droop_control:
  enabled: false
  f_nominal: 60.0
  omega_0: 1.0
  V_0: 1.1
  ref_bus: '1'
  droop_buses: ['1']
  randomize_droop: false
  mp: 0.10
  mq: 0.10
  mp_range: [0.03, 0.05]
  mq_range: [0.02, 0.04]
  frequency_deadband: 0.006
  voltage_deadband: 0.001

load:
  generator: agg_load_profile
  agg_profile: default
  scenarios: 1
  start_scaling_factor: 1.0
  max_scaling_factor: 1.0
  step_size: 0.1
  global_range: 0.0
  sigma: 0.0
  change_reactive_power: false

topology_perturbation:
  type: none

admittance_perturbation:
  type: none

generation_perturbation:
  type: none
